name: Maven Verify

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '15 0 28 * *'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        architecture: x64
        cache: maven
    - name: Test and build Maven project
      run: mvn --batch-mode --update-snapshots verify --file pom.xml
    - name: Upload build artifact
      run: mkdir staging && cp target/*-jar-with-dependencies.jar staging
    - uses: actions/upload-artifact@v4
      with:
       name: Build
       path: staging
  keepalive:

    runs-on: ubuntu-latest

    permissions:
      actions: write

    steps:
    - uses: actions/checkout@v4
    - uses: gautamkrishnar/keepalive-workflow@v2
